#spring boot port is
spring:
  profiles:
    active: local
server:
  port: 8081
---

#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-events
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    template:
      default-topic: library-events

  config:
    activate:
      on-profile: local


---
#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-events
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      #below is the secured cluster server and it will have client.keystore.jws ,and client.truststore.jws file
      #because this is producer and act as client for brokers which is using ssl with server.keystore.jws& server.truststore.jks files bith should have signned secured file using cert file
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
      ssl:
        key-store-location: file:/ filepath for client.keystore.jws
        key-store-password: password
        trust-store-location: file:/ filepath for client.truststore.jws
        trust-store-password: password
      properties:
        security:
          protocol: SSL
          ssl.endpoint.identification.algorithms:
    template:
      default-topic: library-events

  config:
    activate:
      on-profile: preprod
